// Player Search types
export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const RECEIVE_SEARCH_EMPTY = 'RECEIVE_SEARCH_EMPTY';

// Player Profile types

export const REQUEST_MATCH_LIST = 'REQUEST_MATCH_LIST';
export const RECEIVE_MATCH_LIST = 'RECEIVE_MATCH_LIST';
export const RECEIVE_MATCH_LIST_EMPTY = 'RECEIVE_MATCH_LIST_EMPTY';

// Player Summary types
export const REQUEST_PLAYER_SUMMARY = 'REQUEST_PLAYER_SUMMARY';
export const RECEIVE_PLAYER_SUMMARY = 'RECEIVE_PLAYER_SUMMARY';
export const RECEIVE_PLAYER_SUMMARY_EMPTY = 'RECEIVE_PLAYER_SUMMARY_EMPTY';