// Player Search types
export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const RECEIVE_SEARCH_EMPTY = 'RECEIVE_SEARCH_EMPTY';

// Player Profile types

export const REQUEST_MATCH_LIST = 'REQUEST_MATCH_LIST';
export const RECEIVE_MATCH_LIST = 'RECEIVE_MATCH_LIST';
export const RECEIVE_MATCH_LIST_EMPTY = 'RECEIVE_MATCH_LIST_EMPTY';

// Player Summary types
export const REQUEST_PLAYER_SUMMARY = 'REQUEST_PLAYER_SUMMARY';
export const RECEIVE_PLAYER_SUMMARY = 'RECEIVE_PLAYER_SUMMARY';
export const RECEIVE_PLAYER_SUMMARY_EMPTY = 'RECEIVE_PLAYER_SUMMARY_EMPTY';

// Player Peer types
export const REQUEST_PEER_LIST = 'REQUEST_PEER_LIST';
export const RECEIVE_PEER_LIST = 'RECEIVE_PEER_LIST';
export const RECEIVE_PEER_LIST_EMPTY = 'RECEIVE_PEER_LIST_EMPTY';

// Player Hero types
export const REQUEST_HERO_LIST = 'REQUEST_HERO_LIST';
export const RECEIVE_HERO_LIST = 'RECEIVE_HERO_LIST';
export const RECEIVE_HERO_LIST_EMPTY = 'RECEIVE_HERO_LIST_EMPTY';